# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  build:

    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Download cached dependencies
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - install:
          name: Build
          run: yarn install build

      - save_cache:
          name: Cache build
          paths:
            - node_modules
          keys:
          # save dependencies for next build job
          - v1-dependencies-{{ checksum "package.json" }}
          # save build for deploy job
          - v1-build-{{ .BuildNum }}
        
      - test:
          name: Test
          run: yarn test

  deploy:

    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/repo

    steps:
      - restore_cache:
          name: Download build
          key: v1-build-{{ .BuildNum }}

      - run:
          name: Deploy Site
          command: scp ec2-user@ec2-34-207-239-10.compute-1.amazonaws.com:/var/www/html/efs-mount-point/test 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

